name: CI

on:
  push:
    branches:
      - master

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST -H "Authorization: Bearer 1RdG7oQ5GtBN88JCWApJ" https://app.autify.com/api/v1/schedules/690

