name: CI

on:
  push:
    branches:
      - master

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Create issue using REST API
      run: |
        curl POST https://app.autify.com/api/v1/schedules/649 -H "Authorization:Bearer ${{ secrets.Autify_KEY_TOKEN }}"
