name: CI

on:
  push:
    branches:
      - master

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Create issue using REST API
      run: |
        curl --request POST \
        --url https://app.autify.com/api/v1/schedules/649 \
        --header "Authorization:Bearer ${{ secrets.Autify_KEY_TOKEN }}" \
        --header 'content-type: application/json' \
