name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install alpine-curl
        uses: docker://byrnedo/alpine-curl:latest
      - name: curl test
        run: |
         curl -X POST -H "Authorization: Bearer 1RdG7oQ5GtBN88JCWApJ" https://app.autify.com/api/v1/schedules/649
