name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: docker://byrnedo/alpine-curl:latest
    - name: Use curl
      uses: docker://byrnedo/alpine-curl:latest

    - name: run curl
      run: | 
        curl -X POST https://app.autify.com/api/v1/schedules/649 -H "Authorization:Bearer ${{ secrets.Autify_KEY_TOKEN }}"

